gisce/libCNMC

libcnmc/res_4603/FIA.py
libcnmc/res_4603/LAT.py
libcnmc/res_4603/LBT.py
libcnmc/res_4603/MAQ.py

Canviades totes les funciones de get_ccaa_from_municipi, per treure el camp buit dels ids que passàvem.
També s'ha fet el canvi al codi de l'ERP, a el commit de la [NEW_1048](https://github.com/gisce/erp/pull/1611) [#100](https://github.com/gisce/erp/commit/ab5cb971d0df75368c7314a745a9ce88fd005c4a).

Fix get ccaa

---

libcnmc/res_4771/POS.py

* If Normalized tension is 0 or empty, it fails

FIX POS Tension 0 if empty

---

libcnmc/res_4771/MAQ.py

MAQ Capacidad with 3 decimals to avoid precission looses converting kVA to MVA

IMP Capacidad MAQ with 3 decimals

---

libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F15.py

Function now retrieves block name instead of the ID.

get_node fix

---

libcnmc/cir_4_2015/F11.py

Potencia is now calculated by adding the trafo's power that belongs to the CT and have the "appears on inventary" checkbox checked.

LibCNMC 4/2015 - F11 potencia field fix

---

libcnmc/cir_4_2015/F1bis.py

When there're not readings now 0 is printed instead of empty char ' '

libCNMC - Fix F1Bis readings

---

libcnmc/cir_4_2015/F13C.py

Parc now retrieves name from park's code.

[FIX] libCNMC F13C park name

---

libcnmc/cir_4_2015/F12bis.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F15.py
libcnmc/res_4666/CON.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

Implementing the changes provided in the BOE to classify the items correctly in each inventory made by the module.
Filter Criteria:
Also updated the estat classify criteria for all the elements on the 4666.

Update the filters to the new BOE-2017 criteria

---

libcnmc/cir_4_2015/F1.py

Se añade una consulta a la variable res.config con el nombre `libcnmc_4_2015_default_f1` y el valor `{'o_cnae': '9820', 'o_cod_tfa': '416'}` para actualizar el valor del CNAE y la tarifa por defecto. 
Si no se define valor se dejará por defecto.

Añadir posibildad de añadir valores por defecto en el F1 4/2015

---

libcnmc/res_4666/LBT.py

- If a BT element has no data_pm it will not apear on the file

If has not data APM is not shown

---

libcnmc/cir_4_2015/F20.py

* Excluded the CUPS in wich its polisses have a tarifa like 'RE'

Circular 4/2015-F20: Exclude CUPS with tarifa like 'RE'

---

libcnmc/cir_4_2015/F9.py

- Se ha correguido un error al redondear a 3 cifras las coordenadas que causava que el F9 de la 4/2015 saliera vacio.
- F9 de la 4/2015

Revertir canvios en la generacion del F9 de la 4/2015

---

libcnmc/cir_4_2015/F12bis.py

- Fix the search params to exclude the FusibleAT to work correctly to everybody.
- Cir.4/2015: F12Bis

Fix the way that FusAT are excluded.

---

libcnmc/cir_4_2015/F15.py

- Before just the tipus inventari "fiabilitat" were listed. 
- Now all the tipus inventari "fiabilitat" and "l2+p" are listed on the file.
- Cir. 4/2015 : F15.

Include all tipus inventari on F15.

---

libcnmc/cir_4_2015/F15.py

- Before this fix, the X and Y of the file were not initialized, and it was possbile to arrive at the end of the execution without being  instantiated. Now the X and the Y are initialized correctly as an empty string.
- Circ. 4/2015: F15

Fix x,y initialization.

---

libcnmc/cir_4_2015/F15.py

- Get `srid` from  res config instead of get_srid of base geom
- F15

Get SRID from res_config instead of use giscegis function

---

libcnmc/cli_4_2015.py

- Now by default both element types (2l+p and fiabilitat) will be listed on the file.
- Circ. 4/2015: cli_4_2015

Changed the default value for 2l+p i fiabilitat.

---

libcnmc/res_4666/CTS.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/MOD.py
libcnmc/res_4666/SUB.py

- Improve 4666 search parameters to include those elements wich have been 'baixa' but now are active again and have a 'data_baixa' set.
- 4666: 
- F1
- F2
- F3
- F4
- F8
- MOD

Improve search parameters on 4666: F1, F2, F3, F4, F8 and MOD

---

libcnmc/res_4666/LBT.py

- Remove unnecessary and unused code lines from 4666-F2.
- The edges are not used anymore to get the 'origen' and 'desti' of the Tram BT.
- 4666-F2

Remove unnecessary and unused code lines from 4666-F2

---

libcnmc/cir_4_2015/F1bis.py

- En el F1 bis de la 4/2015 solo apareceran las polizas en estado tall, activa y baixa
- F1bis 4/2015

F1bis Solo en estado tall activa and baixa

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F1bis.py
libcnmc/cir_4_2015/F20.py

- The CUPS were being filtered using the polissa. In some cases the CUPS didn't have a related polissa so the library was not able to filter them properly. Now we use the ModCon to made as it should be.
- 4/2015:
- F1
- F1bis
- F11
- F20

Fix the way that the CUPS are filtered on F1, F1bis, F11 and F20.

---

libcnmc/cir_4_2015/F12bis.py

- Hacer que se excluyan las celdas que su tipo sea FUS_AT
- F12bis 4/2015

Modificar criterio de busqueda del F12bis

---

libcnmc/cir_4_2015/F11.py

- En los F11 de la 4/2015 excluir de las salidas de los CTs los interruptores del tipo "INT_BT"
- F11.py

Excluir salidas INT_BT del F11-4/2015

---

libcnmc/utils.py

- Don't cast coords to string since it's done after and it breaks the pyproj transform method because we also replace dots by commas.
- 4/2015: F9

Corregir la generacion del F9 de la 4/2015 en los casos donde se tenia que transformar las coordenades de SRID

---

libcnmc/cli_4666.py

- Eliminar años de la comparativa de datos entregados para el 4666. Comparar con campo único.

Utilizar campo 4666_entregada único.

---

requirements.txt

- Fijar la versión de la librería `pyproj` en las dependencias, para evitar problemas e incompatibilidades.
- `requirements.txt`

Fijar versión de "pyproj" en los requerimientos

---

libcnmc/cir_8_2021/FA1.py

- Ahora busca el "autoconsum_id" de un CUPS utilizando la funcion "get_autoconsum_on_date". De esta manera se obtiene el autoconsumo del CUPS en una fecha determinada y no el "autoconsum_id" actual.
- A1

IMP A1 Obtener el último autoconsumo_id del año

---

libcnmc/cir_8_2021/FA1.py

- Ahora se leen los campos energia_autoconsumida y energia_excedentaria de CUPS y se insertan en el A1. Antes se forzava vacío.
- A1

IMP Lee los campos energia_autoconsumida y energia_excedentaria de CUPS para el A1

---

libcnmc/cir_8_2021/FB1_1.py

- Los puntos del vertex ahora son tratados como float dado que han dejado de ser compatibles con Shpaely como str
- B1.1

FIX Convierte un punto tipo str a float por compatibilidad con Shapely - B1.1 Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Ahora el estado_contrato se calcula únicamente comprobando si existía una modcon en fecha del 'año_formulario-12-31'
- A1

FIX Mejora el cálculo de estado_contrato en el A1 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

- A2, campo CUPS_SERVICIOS_AUXILIARES. Lee si hay algún CUPS de SSAA vinculado al RECORE, si es el caso la usa, si no lo busca en la póliza y si la póliza tampoco lo contiene busca un CUPS que coincida con el de la instalación.
requires https://github.com/gisce/erp/pull/16503
- A2

ADD Lee si hay algún CUPS de SSAA vinculado al RECORE A2 - Cir8/2021

---

libcnmc/cir_8_2021/FB3.py
libcnmc/cir_8_2021/FB3_1.py

- Excluye los registros con criterio_regulatorio = excluir
- Corrige un error al leer 'tensio_const'
- B3, B3.1

IMP Mejoras en B3 y B3.1 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Corrige el valor a 0 si no hay facturas
- A1

IMP Corrige el valor a 0 si no hay facturas - A1 - Cir8/2021

---

libcnmc/cir_8_2021/FB2_2.py

- Excluye los IDs que tengan criterio regulatorio = Excluir
- B2.2

IMP Excluye los IDs que tengan criterio regulatorio = Excluir en B2.2 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py

- OPERACION vacío cuando MODELO = M según el validador de la CNMC
- B1

IMP OPERACION vacío cuando MODELO = M - B1 - Cir8/2021

---

libcnmc/cir_8_2021/FD1.py

- Al cridar la funció `get_ine()` retorna provincia, municipi i s'estava assignant com  a municipi, provincia

Fix provincia, municipi D1

---

libcnmc/cir_8_2021/FA1.py

-  CAU vacío si COD_AUTO in '002', '003', '005', '007' según validador
- A1

IMP CAU vacío si COD_AUTO in '002', '003', '005', '007'

---

libcnmc/cir_8_2021/FB1_1.py

- Corrige el sequence del B1.1 ya que no mostraba elementos de baja durante el año del formulario.
- B1.1

FIX Corrige el sequence del B1.1 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py

- Vacía el valor de las subenciones PRTR para el ejercicio 2022

IMP Vacía el valor de las subenciones PRTR para el ejercicio 2022 - Cir8/2021

---

libcnmc/cir_8_2021/FC3.py

- Protege IDENTIFICADOR si se introduce manualmente un registro y no se rellena - Cir8/2021
- C3

IMP Protege IDENTIFICADOR si se introduce manualmente un registro y no se rellena C3 - Cir8/2021

---

libcnmc/cir_8_2021/FA3.py

- Inicializa a 0 valores para cumplir con el validador A3
- A3

IMP Inicializa a 0 valores para cumplir con el validador A3 - Cir8/2021

---

libcnmc/cir_8_2021/FB1_1.py

- Excluye los IDs con fecha de baja del año de la retribución
- B1.1

ADD Excluye los IDs con fecha de baja del año de la retribución - Cir8/2021

---

requirements.txt

- Fijar el rango de versiones de `cerberus` para PY2 ya que la 1.3.5 no tiene wheel
```
ERROR: Exception:
Traceback (most recent call last):                                                                                                                                                                                                           
File "/home/ci_replicante/.pyenv/versions/2.7.18/envs/peru/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main                                                                                              
status = self.run(options, args) …
```

Fixed cerberus requirements

---

libcnmc/cir_8_2021/FB5.py

- **major**: Major auto version vX._._
- **minor**: Minor auto version v_.X._
- **patch**: Patch auto version v_._.X
- Se utiliza `id_regulatori` siempre que exista en el fichero B5
- `FB5.py`

 Añadir el campo id_regulatori en B5 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- _Hasta ahora se utilizaba el siguiente orden para el cálculo de la tensión para el Formulario A1:_
- _Se usa el de la póliza_
- _Se usa el de modcon_
- _Se usa el que tiene la acometida por trazabilidad_
- Ahora sólo se mirará por lo que tenga la acometida por trazabilidad. En caso de no tener lo deja vacío.
- Se decide dejar el código anterior comentado de momento.
- `FA1.py`

IMP Calculo tension A1 por traza de acometidas

---

libcnmc/cir_8_2021/FB5.py

- Corrige error al hacer `.strip()` cuando `id_regulatori` es `None`
- B5

Fix getting id_regulatori

---

libcnmc/cir_8_2021/FB5.py

- Fallaba al hacer `node_id[1]` si `node_id` era `None`
- B5

Fix B5 getting node_id

---

libcnmc/cir_8_2021/FB1.py

- Corrección al acceder a la propiedad `self.compare_field` eliminada en la v24
- B1

Corrección al acceder a la propiedad compare_field

---

libcnmc/cir_8_2021/FB1.py

- Se utilizaba el F1Res4666 por error y se ha pasado a utilizar el F2Res4666
- B1

Corrección en la comparación del fichero B1 en tramos de baja

---

libcnmc/cir_8_2021/FB6.py

- Se cambia el filtro para que sólo se tengan en cuenta las celdas que sean del tipo 'fiabilidad' y que estén en soportes AT
- B6

B6: Sólo las celdas que esten en soportes AT

---

libcnmc/cir_8_2021/FA1.py

- Solo utilizar la tabla de bloques si no hay geometría en la acometida
- A1

Solo utilizar la tabla de bloques si no hay geometría en la acometida

---

libcnmc/cir_8_2021/FA1.py

- A1: Eliminar vaciar CAU si COD_AUTO '002', '003', '005', '007'
- Reverts: https://github.com/gisce/libCNMC/pull/550
- A1

A1: Eliminar vaciar CAU si COD_AUTO '002', '003', '005', '007'

---

libcnmc/cir_8_2021/FB2_2.py

- Si existe el campo del trasnformador al que actua la celda se utiliza este campo
- En caso de no existir hace el comportamiento antiguo: coger el primer transformador del CT vinculado a la celda
- https://github.com/gisce/erp/pull/19960
- B2.2

B2.2: Se utiliza la trazabilidad si existe el campo

---

libcnmc/cir_8_2021/FD2.py

- Evista la exportación de datos de mas de un año. 
- FD2

FD2: Se exportaban los datos sin distinguir por año

---

libcnmc/cli.py

- Hacer que se pueda ejecutar de forma aislada. Útil para desarrollo. 
- `libcnmc/cli.py`

ADD cobertura para poder ejecutar la libcnmc como script aislado

---

libcnmc/cir_8_2021/FB4.py

- El formulario B4, en cierto momento, debe calcular el valor del campo IDENTIFICADOR_EMPLAZAMIENTO. Éste viene dado por, o bién el nombre del Parque o bién de la Subestación, al que la posición se encuentra asociada.
Segun el BOE-A-2021-21003 debe coincidir al identificador de la S.E. para el formulario B3 o de parque segun el B3.1. 
En el caso de que sea de la subestación (formulario B3) se usaba una cadena fija y debe ser el valor del campo `name` de la SE. 
- B4 -> `libcnmc/cir_8_2021/FB4.py`

FIX nombre subestación en Identificador emplazamiento

---

libcnmc/cir_8_2021/FB4.py

- Arreglar el cálculo del campo Ajena en el formulario B4 de la Circular 8/2021. 
- Tal como se especifica en el texto refundido de la Circular 8/2021, el valor del campo AJENA será 1 si la posición se encuentra ubicada en una Subestación ajena a la distribuidora. 
Es decir, en aquellos casos en los que, en la Subestación, el campo `Propietario` se encuentra desmarcado.
[Arreglo del cálculo del campo AJENA del formulário B4](https://rfc.gisce.net/t/arreglo-del-calculo-del-campo-ajena-del-formulario-b4/2010)
- B4 -> `libcnmc/cir_8_2021/FB4.py`

FIX calculo campo ajena en formulario B4 Circular 8_2021

---

libcnmc/cir_8_2021/FB1.py

- Cuando se tiene un tramo sin fecha APS pero éste forma parte de un Trabajo de Inversión saltaba error `IndexError: list index out of range` en el momento de calcular el valor de la fecha de la inversión parcial.
- B1

FIX comparar fecha de obra con fecha aps inexistente

---

libcnmc/cir_8_2021/FB1.py

- Cuando se tiene un elemento de BT sin fecha APS pero éste forma parte de un Trabajo de Inversión saltaba error `IndexError: list index out of range` en el momento de calcular el valor de la fecha de la inversión parcial.
- B1

FIX comparar fecha de obra con fecha aps inexistente en elementos BT

---

libcnmc/cir_8_2021/FA1.py

- Arreglar el hecho de leer y comprobar el campo `node_id` en el CUPS al generar el A1 
- A1

FIX Hacer que no se revise si el CUPS tiene nodo al generar el A1

---

libcnmc/cir_8_2021/FD2.py

- Se ha corregido la búsqueda de valores para la Z8_01 para que use unicamente los del año a exportar
- FD2

Exportar unicamente datos de el año actual en Z8_01

---

libcnmc/cir_8_2021/FB2.py

- En la PR del ERP #19873(https://github.com/gisce/erp/pull/19873) se añade un nuevo campo `tensio_entrant` que va a ser el sustituto del original `tensio_p` en los CTs. Esto ayuda en el sentido que pasamos de un campo texto a un `many2one` contra el modelo de tensiones normalizadas.
- Esta PR modifica el B2 para que intente sacar la tensión del campo nuevo si existe.
- B2

ADD Cobertura para el nuevo campo de tension entrante en CT en B2

---

requirements.txt

Actualiza los requerimientos para python 3, de momento la ibreria no es compatible pero ahora se puede instalar

Update requirements for py3

---

libcnmc/cir_8_2021/FB4.py

- Si existe Trabajo relacionado a una posición pero el valor residual es 0, el campo debe aparecer como vacío
- B4

FIX valor residual de cero a vacio

---

libcnmc/cir_8_2021/FA3.py

- Realizar ajuste para que las coordenadas X e Y, resultado del nodo especificado en el modelo de previsión de crecimiento, sean siempre en SRID 25830
- A3

FIX valores coordenadas X e Y transformadas a SRID 25830

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB6.py

Si una instalación se declara como modelo M y decide no volver a declararse en ejercicios posteriores, no es necesario darla de baja de manera formal. Bastará con no declararla en el ejercicio que corresponda. Así, para conseguir esta condición se desarrolla la siguiente mejora:
- En los formularios sobre instalaciones (formularios B) que contienen el campo `MODELO` y su valor es `'M'` excluir aquellos dados de baja en el año a retribuir.
- B1, B2, B4 y B6

IMP excluir de los ids a consumir las bajas de modelo M

---

libcnmc/cir_8_2021/FA2.py

- FIX error en llamada a función en la que no se pasan correctamente los parámetros para poder especificar el `context` y así incluir los registros no activos
- A2

FIX llamada a funcion para inactivos usando context A2

---

libcnmc/cir_8_2021/FA2.py

- Para Autoconsumos colectivos se fija el valor del campo `AUTOCONSUMO` a 2
- A2

FIX valor 2 en A2 para autoconsumos colectivos

---

libcnmc/cir_8_2021/FA2.py

- Hacer que los valores resultantes que se generan para las energías venga con un formato de coma ('`,`').  
- A2

A2: FIX los valores de las energias en decimales con coma

---

libcnmc/cir_8_2021/FA2.py

- Hacer que los valores de tensión se generen en kV y no V como lo está haciendo ahora
- A2

A2: FIX valores de tension en kV

---

libcnmc/cir_8_2021/FB1.py

- Obtener el valor del campo `operacion` en los tramos de AT y los elementos de BT para darle valor al campo `OPERACION` del fichero B1
- B1

IMP cobertura en el campo operacion para B1

---

libcnmc/cir_8_2021/FA1.py

- En generar la casilla L15 hay que tener en cuenta que POTENCIA_ADSCRITA>=POTENCIA_CONTRATADA
- A1

FIX potencia adscrita inferior a contratada

---

libcnmc/cir_8_2021/FA2.py

- En el renombrado para el tratamiento de los generadores de autoconsumo (AC) se usaba una variable incorrecta -la de AC en vez de los ids de generadores-.
- A2

FIX renombrado generadores en A2

---

libcnmc/cir_8_2021/FA2.py

- No existe valor `2: Autoconsumo colectivo` en el campo de `AUTOCONSUMO` en el A2. Se confundió por el de la explicación aclaratoria del A1 en el FAQ de 2024 de la Circular 8/2021.
- Para los registros correspondientes a Generadores de Autoconsumo procedentes de autoconsumo colectivo se fija su valor a `1: Con autoconsumo`.
Error procedente de https://github.com/gisce/libCNMC/pull/666
- A2

FIX fijar valor autoconsumo a 1 para generadores AC A2

---

libcnmc/cir_8_2021/FA2.py

- Arreglar la captación de la tensión de tipo cadena de carácteres en la acometida y que luego hay que dividir para mover la coma.
PR ERROR https://github.com/gisce/libCNMC/pull/662
- A2

Arreglar captacion tension de tipo cadena en acometida para ACs

---

libcnmc/cir_8_2021/FA1.py

- Revisar si el autoconsumo (AC) se encontraba activo en el año a retribuir. Hasta ahora se incluía todo aquel que fuera asociado a un CUPS, tuviera o no activa el AC en la póliza. Esto implicaba, por ejemplo, que se añadiera los datos de ACs en borrador.
- A1

Revisar si el Autoconsumo esta activo para retribucion

---

libcnmc/cir_8_2021/FB2.py

Segun el validador de la Circular, si existe inversión y, por tanto `TIPO_INVERSION` tiene valor, entonces es obligatorio especificar `FINANCIADO`. Ahora bién, no se trata de un campo obligatorio. Hasta ahora se le daba igualmente valor 0. Lo cual no es necesariamente erróneo pero sí poco claro. 
- Se realiza un cambio de comportamiento específico. Cuándo el `TIPO_INVERSION` está vacío, `FINANCIADO` se generará también vacío.
- TASK-71736
- B2

Si TIPO INVERSION vacio FINANCIADO tambien

---

libcnmc/cir_8_2021/FB2.py

- Eliminar toda lógica de cálculo del campo `CAUSA_BAJA` del Centro Tranfromador para que venga dado directamente del valor especificado en el TI del Trabajo si procede o forzar a `0: No causa baja` en caso contrario.
- B2

Extraer el valor de CAUSA_BAJA del valor del TI del Trabajo

---

libcnmc/cir_8_2021/FB5.py

- El archivo generaba datos para máquinas que se les habia especificado `criterio_regulatorio = forzar excluir`
- B5

No tener en cuenta las maquinas excluidas B5

---

libcnmc/cir_8_2021/FA1.py

- Cuando un contrato asociado a un CUPS se encuentra en estado modificación contractual, el generador de la Circular no lo tiene en cuenta. Y es que, hasta ahora, solamente se consideran válidos, para obtener los datos, aquellas modificaciones contractuales en la que el contrato está en estados: `corte`, `activos`, `baja`.
- Se añade también `impagados` como estado válido.
- Se aprovecha para eliminar duplicidades en código
- A1

Añadir los CUPS en contratos con estado modificacion contractual

---

libcnmc/cir_8_2021/FA1.py

Se añadieron estados válidos al obtener los registros para generar el A1 >> https://github.com/gisce/libCNMC/pull/690
- Se trata de estados requeridos también en el momento de obtener la información registro a registro. Casos como los campos CNAE o COD_TFA. Así, la presente funcionalidad agrega estados válidos en el momento de recoger la información de los contratos cuando se genera el formulario A1.
- A1

Añadir esatdos validos al recoger informacion de contratos

---

libcnmc/cir_8_2021/FA1.py

- Se elimina el filtro de fecha de creación de los CUPS de este modo si un CUPS se crea el año siguiente de la retribución, pero con intención de ser usado para el año a retribuir, se incluirán igualmente
- A1
TASK-[75302](http://erp-ti.cloudvpn/action?model=project.task&views=%5B%5B999%2C%22graph%22%5D%2C%5B263%2C%22tree%22%5D%2C%5B1129%2C%22form%22%5D%5D&title=Les+meves+tasques+actuals&initialView=%7B%22id%22%3A1129%2C%22type%22%3A%22form%22%7D&action_id=759&action_type=ir.actions.act_window&res_id=75302&treeExpandable=false&limit=80&actionRawData=%7B%22domain%22%3A%22%5B%28%27user_id%27%2C+%27%3D%27%2C+uid%29%2C%28%27state%27%2C%27in%27%2C%28%27open%27%2C%27draft%27%29%29%2C+%28%27stage_id.name%27%2C+%27%21%3D%27%2C+%27Permanent%27%29%5D%22%7D)

Descartar el filtro de fecha de creación en los CUPS

---

libcnmc/cir_8_2021/FB2_2.py
libcnmc/cli_8_2021.py

- Incluir opcionalmente todos los elementos de tipo **Fusible AT** en la exportación de **Celdas y Elementos de Corte** que por defecto estaban excluidos
- B2.2

Nuevo flag para incluir elementos de tipo Fusible AT en el fichero B2.2
