gisce/libCNMC

libcnmc/res_4603/CTS.py
libcnmc/res_4603/DES.py
libcnmc/res_4603/FIA.py
libcnmc/res_4603/LAT.py
libcnmc/res_4603/LBT.py
libcnmc/res_4603/MAQ.py
libcnmc/res_4603/POS.py
libcnmc/res_4603/SUB.py
libcnmc/utils.py

Utilitzem les dades administratives per generar els llistats de la resolució 4603
Aprofitem per millorar el càlcul de comunitat autònoma

Imp data pm propietari

---

libcnmc/res_4603/MAQ.py

Error al fer la validació ja que perc_finacament si és 0.0 és False

Error validació perc_financament

---

libcnmc/res_4771/LAT.py
libcnmc/res_4771/LBT.py

* LAT Tension in kV, then factor 1000 instead 1000000
* LBT float capacity in kVA instead of MVA, then factor 1000 instead 1000000.
* LBT 1.0 if capacity is 0.0

FIX LINES capacidad bad calculation

---

libcnmc/res_4771/LAT.py
libcnmc/res_4771/LBT.py
libcnmc/utils.py

To avoid total longitud loosing, we use 3 decimals

IMP longitud with 3 decimals, PEP8ing

---

libcnmc/res_4771/CTS.py
libcnmc/res_4771/FIA.py
libcnmc/res_4771/LAT.py
libcnmc/res_4771/LBT.py
libcnmc/res_4771/MAQ.py
libcnmc/res_4771/POS.py
libcnmc/res_4771/SUB.py

List of changes from gisce/erp#2148

Update resolution 4771 

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F12bis.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F14.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F1bis.py
libcnmc/cir_4_2015/F20.py
libcnmc/utils.py
setup.py

libCNMC 4/2015

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F14.py

Fixed float divisions that caused some errors.

libCNMC 4/2015: Fix float divisions

---

libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F15.py

Removed some unnecessary format_f.

libCNMC 4/2015: SRID fixed

---

libcnmc/cir_4_2015/F11.py

Fixed tension field: if it contains a numeric value keeps it empty.

Tension field F11

---

libcnmc/cir_4_2015/F1.py

zona_desc has been fixed, now checks if CT haves zona_id before trying to retrieve it.

zona_desc fix for F1 form

---

libcnmc/cir_4_2015/F9.py

Fix BT layer

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F9.py

SRID fixed: point has been initialized.

---

libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F15.py

Fix SRID: vertex initialized.

---

libcnmc/cir_4_2015/F1.py

Vertex is now a list of two elements instead of a dictionary.

Fix SRID vertex

---

libcnmc/cir_4_2015/F15.py

Reliability element field has been fixed: now it retrieves the cell's name.

Reliability element field fix

---

libcnmc/utils.py

get_ine error when INE is unknown has been fixed.

get_ine fix

---

libcnmc/cir_4_2015/F12.py

The node of the trafo in F12 was the CT node. Now is the node of the trafo

IMP trafo node instead of CT node

---

libcnmc/cir_4_2015/F1.py

Fix vertex

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py

It checks if the provincia exists before retrieving.

Provincia field fix.

---

libcnmc/cli.py

Updating CUPS and Meters has been fixed.

CNMC Update data fix

---

libcnmc/cli.py
libcnmc/core/backend.py

[The cursor is never commited](https://github.com/gisce/libCNMC/blob/master/libcnmc/core/backend.py#L171)
Fixes #101

Commit transaction when using native API

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F12.py

Fixed F1 and F12 decimal fields.
Now prints commas ',' instrad of points '.'

Fix F1 and F12 decimal separator

---

libcnmc/res_4771/POS.py

Substation code is now the substation description instead of its name.

Substation code field fix

---

libcnmc/cir_4_2015/F11.py

"used outputs" and "max outputs" fields fix

---

libcnmc/cir_4_2015/F1.py

F1 node has been fixed. Now script retrieves the node from Giscegis_nodes instead of Giscegis_edge.

F1 node fix

---

libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F15.py

Municipi and Provincia fields fix.

---

libcnmc/core/backend.py

This try to fix open connections. Please test and test before to release it.

Try to fix connections with __del__ method

---

libcnmc/cir_4_2015/F1.py

F1 node "B" tag has been removed.

F1 node tag fix.

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py

Resistance and reactance are now correctly calculated.

Resistance and reactance fix

---

libcnmc/cir_4_2015/F15.py

Tram field fix

---

libcnmc/cir_4_2015/F9.py

F9 output fix

---

libcnmc/checker.py
setup.py

CNMC 4/2015 files checker script has been added to library.

CNMC 4/2015 files checker

---

libcnmc/checker.py

Using "with open" instead of "open".

libCNMC 4/2015 Checker

---

libcnmc/checker.py

Script now checks if all F1bis CUPS appears on F1.

LibCNMC 4/2015 - Checker script improvements

---

libcnmc/checker.py

Script now checks if not null fields are filled in forms F1, F1BIS, F2A, F2B and F10.

LibCNMC 4/2015 Checker enhancement

---

libcnmc/checker.py

Script now shows line instead of tram when tram is null in F10 not null test.

4/2015 libCNMC Check script

---

libcnmc/res_4771/MAQ.py
libcnmc/res_4771/POS.py

The following files has been fixed:
POS: code and description has been fixed.
MAQ: description has been fixed.

4771 resolution fix

---

libcnmc/checker.py

F10 check has been fixed.
Now displays the correct line of each missing field.

libCNMC 4/2015 checker F10 fix

---

libcnmc/cir_4_2015/F13C.py

1st field now shows substation code instead of position code.
2nd field now shows position code instead of position type.

libCNMC 4/2015 - F13 position fields fix

---

libcnmc/res_4771/POS.py

CT description has been fixed.

libCNMC - 4771 POS - CT description fix

---

libcnmc/cir_4_2015/F12.py

F12 form now retrieves non reductor trafos only.

libCNMC - 4/2015 F12 reductor fix

---

libcnmc/cir_4_2015/F15.py

Added "A" character in tram field.

libCNMC 4/2015 - Fix F15 tram field

---

libcnmc/cir_4_2015/F14.py

Some fields has been corrected. Now are not divided by 1000.

libCNMC - FIX F14 energy fields

---

libcnmc/checker.py

F12 node check has been disabled.

libCNMC 4/2015 checker - F12 node check disable

---

libcnmc/cir_3_2015/F3.py
libcnmc/cir_3_2015/__init__.py
libcnmc/cli.py

F3 3/2015 form added.
Related with https://github.com/gisce/erp/issues/2288

libCNMC Circular 3/2015 - Formulari F3

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py

If length in F10AT and F10BT is 0 now returns an string with 0,001 value

libCNMC - Fix F10 length round

---

libcnmc/cir_4_2015/F16.py
libcnmc/cir_4_2015/__init__.py
libcnmc/cli.py

NEW libCNMC F16

---

libcnmc/utils.py

FIX tallar_text function with try/except statement
SENTRY: http://sentry.gisce.net/erp/peusa/group/10360/

FIX libCNMC 4771 "tallar_text" function

---

libcnmc/cli.py
libcnmc/res_4771/LAT.py
libcnmc/res_4771/LBT.py

Deixem escollir si es volen posar els embarrats o no als llistats LAT i LBT de la 4771

Custom embarrats

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F16.py

This PR fixes some decimal fields that don't have 3 required decimal places.

[FIX] Decimal fields

---

libcnmc/cir_4_2015/F10BT.py

Get tipus cable method has been fixed

[FIX] libCNMC F10 BT type field

---

setup.py

Quick patch to avoid this problem
https://github.com/gisce/libCNMC/issues/172

Force cerberus version

---

libcnmc/cir_4_2015/F13bis.py

F13Bis now retrieves data from Parks instead of Substations

[FIX] F13 Bis "Parcs"

---

libcnmc/cir_4_2015/F13bis.py

- Use cini from parc model instead of subestacio

Use cini from parc instead of subestacio

---

libcnmc/cir_4_2015/F13bis.py

Improve python 3 compatibility

---

libcnmc/res_4131/CTS.py
libcnmc/res_4131/FIA.py
libcnmc/res_4131/LAT.py
libcnmc/res_4131/LBT.py
libcnmc/res_4131/MAQ.py
libcnmc/res_4131/POS.py

Imp switch ti field for atuocalculated field

---

libcnmc/res_4131/CTS.py

- Removes old usage of TI field

Remove old field ti

---

libcnmc/models/cnmcmodel.py
setup.py

Apply this according the Cerberus doc:
http://docs.python-cerberus.org/en/stable/upgrading.html#data-types
Fixes https://github.com/gisce/libCNMC/issues/172

Improve cerberus compatibility

---

libcnmc/models/res_4131/f2_4131.py
libcnmc/res_4131/LBT.py

Fix BT comparsion

---

libcnmc/models/res_4131/f1_4131.py
libcnmc/models/res_4131/f4_4131.py

- Fix F1 compare fields
- Fix F4 compare fields

Fix compared fields

---

libcnmc/models/res_4131/f1_4131.py
libcnmc/models/res_4131/f2_4131.py
libcnmc/res_4131/LAT.py
libcnmc/res_4131/LBT.py

- Remove field propiedad on F1
- Remove field propiedad on F2

Update generation of 4131

---

libcnmc/models/res_4131/f1_4131.py
libcnmc/models/res_4131/f2_4131.py
libcnmc/res_4131/LAT.py
libcnmc/res_4131/LBT.py

This reverts commit e717fd5077a36facd1b60e8f2a184fda97760719.

Revert "Remove field propiedad on F1 and F2"

---

libcnmc/res_4667/RES.py

- Fixes error to generate  res file

Remove return of res

---

libcnmc/res_4771/INV.py

Improve documentation

---

libcnmc/res_4771/CTS.py

Improve code of 4771

---

libcnmc/cli.py
libcnmc/res_4666/MOD.py
libcnmc/res_4666/__init__.py
libcnmc/utils.py
setup.py

- Add suport to generate the modification file of 4666

Add 4666_mod

---

libcnmc/cir_4_2015/F1.py

Only get the CNAE Code

---

libcnmc/res_4666/CON.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

Change precision from 3 to 2 decimals

Fix precision of financiado

---

libcnmc/res_4667/RES.py

This PR fixes the field demanda_empresa_p0. If applied, it will not be longer than 8 digits.

4667 RES file decimal length

---

libcnmc/cir_4_2015/F1.py

TO DO:
Si els següents camps no estan informats, obtenir de la ultima modificació contractual (activa o no):
- CNAE (E)
- COD_TFA (G)
- Tensió d'alimentació (N)
- Potència contractada (P)
En cas de no existir modificació contractual:

F1 4/2015 improvements

---

libcnmc/cir_4_2015/F15.py

Updated the filter of the 4/2015-F15.
Changes: 
+Field "inventari" not contemplated.
+Deleted the distinction of CTS and AT-Suports.

Update filter 4 2015 f15

---

libcnmc/cir_4_2015/F15.py
libcnmc/utils.py

- Project ct coords of F15 to 25830
- Add docstrings

Project ct coords of F15 to 25830

---

libcnmc/cir_4_2015/F15.py

Contemplate the node value for the cts elements on the F15 of the 4/2015.

Add function to find node name in cts elements.

---

libcnmc/res_4666/POS.py

Improved the generation of the inventori F4-Posicions of the 4666.

Improve the generation of the 4666-F4.

---

libcnmc/res_4666/LAT.py

* Added the field **conductors** as a field to be read for the inventory.
* Changed the hardcoded value of the 12th value of the inventory by the new **conductors** value read from the DB. If the value is not set on the DB is set to 1 by default.

Fixed the hardcoded field by the DB value.

---

libcnmc/cir_4_2015/F15.py

Get the value of the field from an element Cella if the field is not empty, otherwise the value will be retrieved of the element At.Suport.

Fixed a problem with the value of the field tensio.

---

libcnmc/cir_4_2015/create_celles.py

*  Updated the script adding support for the new fields circuits.

Update the script to create celles from the values in a CSV

---

libcnmc/cli_4666.py

- Fix the imports from 4131 to 4666

Fix imports

---

libcnmc/cli_4666.py

- Change the comparsion file `4131_entregada_xxxx` to  `4666_entregada_xxxx` 
- To compare with the last year of 4666

Actualizar los campos de comparacion

---

libcnmc/res_4666/LBT.py

- Fixes typo error on the docstring

Fix typo error on the docstring

---

libcnmc/res_4666/AUD_CTS.py
libcnmc/res_4666/AUD_FIA.py
libcnmc/res_4666/AUD_LAT.py
libcnmc/res_4666/AUD_LBT.py
libcnmc/res_4666/AUD_POS.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

- Remove references of 4131 of 4666

Actualitzar generacion de 4666

---

libcnmc/res_4666/LBT.py

Arreglar la generacion de LBT de 4666

---

libcnmc/models/res_4666/f1_4666.py
libcnmc/models/res_4666/f2_4666.py
libcnmc/models/res_4666/f3_4666.py
libcnmc/models/res_4666/f4_4666.py
libcnmc/models/res_4666/f5_4666.py
libcnmc/models/res_4666/f6_4666.py
libcnmc/models/res_4666/f7_4666.py
libcnmc/models/res_4666/f8_4666.py

Arreglar docstrings

---

libcnmc/res_4666/POS.py

Arreglar comparacion de la 4666

---

libcnmc/cir_4_2015/F10AT.py

- Add voltage on the nodes that hav a reductor
- Because single node can't hav multiple voltages

Añadir tension al nodo si coincide con un tranformador reductor

---

libcnmc/res_4666/LAT.py

- Exclude the trams with longitud_cad with more than 100m

Exclude embarrats of more than 100m 

---

libcnmc/res_4666/LAT.py

- Fix to ensure the at tram has value in `tensio_max_disseny_id`

Fix get tensio_max_disseny

---

libcnmc/res_4666/LAT.py

- Fix read of the id of the tension

Fixes the read of the tension 

---

libcnmc/res_4666/LAT.py

- If is baixa and has not data_baixa dont apear

Remove trams that are baixa and data_baixa is empty

---

libcnmc/models/res_4666/f6_4666.py

- Changes the type of valor_inversion
- To fix the comparsion of the values

Fix type of valor_inversion

---

libcnmc/cli.py

Arreglar documentacion

---

libcnmc/cir_4_2015/F1.py

Improve docstrings 4/2015

---

libcnmc/cir_4_2015/F1.py

- Precalculate the municipis ines before fixes https://github.com/gisce/libCNMC/issues/302
- Calculate the default cnae and default cod_tfa before instead on the loop

Mejorar generacion del F1 y F1bis de la 4/2015

---

libcnmc/cir_4_2015/F9.py
libcnmc/utils.py

- Round the position to 3 decimals instead of 6
- Add docstrings 
- Reformat code

Improve the F9 Generation

---

libcnmc/cir_4_2015/F1.py

- Switch municipi and provincia fields 
- Use more clear var names

Switch fields municipi and provincia

---

libcnmc/cir_4_2015/F1.py

- Make comparation on https://github.com/gisce/libCNMC/blob/fix_pot_ads_comp/libcnmc/cir_4_2015/F1.py#L376 with float instead of str

Compare with float instead of str

---

libcnmc/cir_4_2015/F11.py

- Don't include RE and RE12 polisses on the F11 energy

Don't include RE polisses on energy of F11

---

libcnmc/cir_4_2015/F1.py

* Removed old way to retrieve the code.
* Implement the new way of retrieving the code as is made on the F11. 
* Now, the field is filled with [MunCode+DC] using the get_ine function from utils.

Fix "codi ine municipi" on F1 4/2015

---

libcnmc/cli_4666.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/POS.py

* Adde the "--extended" option to the following inventories for the 4666 adding the specificated fields:
* F1: provincia
* F2: municipi, zona
* F4: provincia, municipi
* F8: provincia, municipi, zona 
* F7: provincia, municipi, zona

Add extended option to 4666

---

libcnmc/cir_4_2015/F12bis.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F15.py

- Filters F12bis  by `[inventario=fiablitat ][intalacio=ct]`
- Filters F13C by `[interruptor = automatico]`
- Filters F15  by `[inventario=fiablitat ][intalacio=at.suport]`

Imp f12bis f13c f15 42015

---

libcnmc/utils.py

- Rename connection variable according `pep8`

Rename connection variable

---

libcnmc/utils.py

- Fixes the identation of the utils file

Fix identation of utils

---

libcnmc/cir_4_2015/create_celles.py

- Add exception message on the raise

Add exception message to raise

---

libcnmc/cir_4_2015/F1.py

Add f1 docstrings

---

libcnmc/utils.py

Improve comments acording pep8

---

libcnmc/cir_4_2015/F1.py

- Usar el campo `potencia_adscrita` dep cups en lugar del campo 
- F1bis

Usar el campo potencia adscrita en lugar del campo del boletin

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F1bis.py

> 0: El punto de suministro no ha estado dado de baja en ningún periodo a lo largo del año 
> 1: El punto de suministro ha estado dado de baja en algún periodo del año

Improve F1 and F1bis

---

.github/pull_request_template.md

- Añadir template para la pull request

Añadir template para la pull request

---

libcnmc/cir_4_2015/F1.py

- Arregla el campo zona del F1 cuando el CT esta de baja
- F1

Arreglar campo zona del CT cuando el CT esta de baja

---

libcnmc/cir_4_2015/F12bis.py
libcnmc/cli_4_2015.py

- Añadir opcion para solo generar fiabilidad en el F12bis
- F12bis

Añadir opcion para poder escojer si solo se quiere que aparezcan elementos de fiabilidad en el F12

---

libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/__init__.py
libcnmc/cli_4_2015.py
libcnmc/utils.py

- Mejorar la generacion del fichero F15 incluyendo posiciones receptoras sin itnerruptor automatico
- F15

Mejorar la generacion del fichero F15 incluyendo posiciones 

---

libcnmc/cir_4_2015/F15.py

-  Arreglar unidades de tension
- F15

Arreglar unidades de tension

---

libcnmc/cir_4_2015/F15.py

- Hacer cast del campo propiedad del F15
- F15

Improve F15 propietari

---

libcnmc/cir_4_2015/F15.py

- Arreglar tension vacia en F15
- F15

Arreglar tension vacia en F15

---

libcnmc/cir_4_2015/F1.py

- Hacer que la lectura sea mas robusta
- F1 4/2015

Mejorar la lectura de la potencia adscrita

---

libcnmc/cir_4_2015/F1.py
libcnmc/utils.py

- Mejorar legibilidad del F1 de la 4/2015
- F1 4/2015

Mejorar legibilidad del codigo F1 4/2015

---

libcnmc/utils.py

- Evitar el reuso de los mismos nombres de variable
- F1

Evitar el reuso de los mismos nombres de variable

---

libcnmc/cir_4_2015/F10AT.py

- Se ha modificado la generacion del F10. Se ha dejado de consultar un campo obsoleto y se ha modificado la codificacion del tipo para los embarrados de LAT.
-  F10 de la 4/2015

Mejorar la generacion del F10 de la 4/2015

---

libcnmc/cir_4_2015/F15.py

- The way that the tensio is retrieves have been modified to adapt it to the use of Tensions Normalitzades.
- F15 de la 4/2015

Fix cel·la tensio retrievment on F15.

---

libcnmc/cir_4_2015/F12bis.py
libcnmc/cli_4_2015.py

- Decide which tipus installacio will be included into the file.
- Cir.4/2015: cli_4_2015.py
- Cir.4/2015: F12bis.py

Improve F12Bis 4/2015: Decide which tipus installacio will be included into the file.

---

libcnmc/cir_4_2015/F10BT.py

- Fix codificacion on F10bt for the field o_tipus
- F10bt

Fix codificacion on F10bt for the field o_tipus

---

libcnmc/cir_4_2015/F13C.py
libcnmc/cli_4_2015.py

- Added an option to the generation of the file F13C of the cir.4/2015 to choose if all the Pos or only the ones with Int.Auto will be included.
- Circ. 4/2015: F13c
- Circ. 4/2015: cli_4_2015

Add options to 4 2015 f13c

---

libcnmc/cir_4_2015/F16.py

- Use the node from giscegiselement[at|bt] instead of the ct
- F16

Mejorar la obtencion del nodo

---

libcnmc/res_4666/CON.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py
libcnmc/utils.py

-  Añade codigo para forzar la inclusion o exclusion de elementos
- 4666/CON
- 4666/CTS
- 4666/DES
- 4666/FIA
- 4666/LAT
- 4666/LBT
- 4666/MAQ
- 4666/POS
- 4666/SUB

Añadir opcion para el check regulatorio

---

requirements.txt

- Force click version lower than 7.0

Force click version lower than 7.0

---

libcnmc/res_4666/FIA.py

-  Obtener municipio a partir del tramo 
- Fiabilidad (7)

Improve get municipi of fia

---

libcnmc/utils.py

Fix on oop

---

libcnmc/res_4666/LAT.py

Improve casting

---

libcnmc/res_4666/LBT.py
libcnmc/res_4667/PRO.py
libcnmc/res_4667/RES_CCAA.py

- Pasar parametros a leer
- Ninguno

Mejorar compatibilidad con ERPPeek

---

libcnmc/cir_4_2015/F1.py

-  Asegura que el CNAE se llenara , o con el en fecha 31-12-2017 o el actual
- F1

Asegura que el CNAE se llena

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F12bis.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F14.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F16.py
libcnmc/cir_4_2015/F1bis.py
libcnmc/cir_4_2015/F20.py
libcnmc/cli_4_2015.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

- Añadir opcion para reducir cups a 20 caracteres
- F1 4/2015
- F1bis 4/2015
- F20 4/2015

Añadir opcion para reducir cups a 20 caraceres

---

.gitignore

- Añadir vscode a git ignore 
- Ninguno

Añadir vscode a git ignore

---

libcnmc/res_4666/POS.py

- Fix rounding on field FINANCIADO of F4-4666. 
- F4 of the 4666

Fix rounding on field FINANCIADO of F4-4666

---

libcnmc/models/res_4666/f1_4666.py
libcnmc/models/res_4666/f2_4666.py
libcnmc/models/res_4666/f3_4666.py
libcnmc/models/res_4666/f4_4666.py
libcnmc/models/res_4666/f5_4666.py
libcnmc/models/res_4666/f6_4666.py
libcnmc/models/res_4666/f7_4666.py
libcnmc/models/res_4666/f8_4666.py

- Add 'fecha_aps' as a field to compare for all Files of 4666.
- All F's

Add 'fecha_aps' as a field to compare for all Files of 4666.

---

libcnmc/res_4666/SUB.py

- Don't count posicions on SE if the field 'criteri_regulatori' is 'excloure'.
- 4666, F3

4666,F3: Don't count posicions on SE if the field 'criteri_regulatori' is 'excloure'.

---

libcnmc/cli_4666.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py

- Add new param '-pf,--prefix' on 4666: F1, F2 and F7
- 4666-F1
- 4666-F2
- 4666-F7

Add new param '-pf,--prefix' on 4666: F1, F2 and F7

---

libcnmc/cli_4666.py
libcnmc/res_4666/LAT.py

- Add divide circuits multiples lenght option on 4666 F1
- 4666: F1

Add divide circuits multiples lenght option on 4666 F1

---

libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py

- Avoid None on prefix for 4666: F1, F2 and F7
- 4666-F1
- 4666-F2
- 4666-F7

Avoid None on prefix for 4666: F1, F2 and F7

---

libcnmc/models/res_4666/f1_4666.py
libcnmc/models/res_4666/f2_4666.py

- Fix the `ref` function of the 4666 F1 and F2.
- 4666-F1
- 4666-F2

Fix the 'ref' function of the 4666 F1 and F2.

---

libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

- Ensure the right format for the field FINANCIADO.
- 4666:
- F1
- F2
- F3
- F4
- F5
- F6
- F8

Ensure the right format for the field FINANCIADO.

---

libcnmc/cir_4_2015/F16.py

- Avoid crash on 4/2015-F16 if it's not possible to find the element on the GIS tables
- 4/2015-F16

Avoid crash on 4/2015-F16 if it's not possible to find the element on the GIS tables

---

libcnmc/cir_4_2015/F9.py
libcnmc/cli_4_2015.py

- Add an option to generate the 4/2015-F9 in an alternative format
- 4/2015-F9

Add an option to generate the 4/2015-F9 in an alternative format

---

libcnmc/res_4666/LBT.py

- Fix origen final fields for 4666-F2.
- 4666-F2.

Fix origen final fields for 4666-F2.

---

libcnmc/utils.py

- Use **active_test** on search for force elements.
- Utils

Use active_test on search for force elements

---

libcnmc/cli_4_2015.py

- Arreglar error tipografico
- F11 4/2015

Fix 4 2015

---

libcnmc/res_4666/LBT.py

Fix on get_edge_id

---

libcnmc/cli_4666.py
libcnmc/core/__init__.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py
libcnmc/utils.py

- Se crea un fichero nuevo con todos las explicaciones para los elementos con estado 1.
- CTS 4666
- DES 4666
- FIA 4666
- LAT 4666
- LBT 4666
- MAQ 4666
- POS 4666
- SUB 4666

Crear fichero nuevo con información referente a los elementos con estado 1

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F16.py
libcnmc/utils.py
requirements.txt

-  Usar node_id para el nombre d elos nodos si esta disponible
- F1 4/2015
- F11 4/2015
- F12 4/2015
- F13bis 4/2015
- F15 4/2015

Usar node_id para el nombre d elos nodos si esta disponible

---

libcnmc/cir_4_2015/F1bis.py

Mejorar docstrings

---

libcnmc/cir_4_2015/F13.py

- Hacer que se compruebe si la subestacion tiene `x` y `y`
- F13 4/2015

Comprobar x y y de la subestacion

---

libcnmc/cir_4_2015/F13.py

- Arreglar error tipografico
- F13

Arreglar error tipografico

---

libcnmc/cir_4_2015/F1bis.py

- Filter the polisses on the F1bis properly since the filter of the state was not being applied to the right model.
- cir_4_2015/F1bis.py

Filter the polisses on the F1bis properly

---

libcnmc/cir_4_2015/F1.py

- Arreglar la obtencion del nodo en el F1 de la 4/2015
- F1 4/2015

Arreglar la obtencion del nodo en el F1 de la 4/2015

---

libcnmc/cir_4_2015/F12.py

- Arreglar lectura del node_id del fichero F12
- F12 4/2015

Arreglar lectura del node_id del fichero F12

---

libcnmc/cir_4_2015/F15.py

- Arreglar la escritura del nodo de F15
- F15 4/2015

Arreglar la escritura del nodo de F15

---

libcnmc/cir_4_2015/F1.py

- Arreglar F1 al comprobar el nodo
- F1 4/2015

Arreglar F1 al comprobar el nodo

---

libcnmc/cir_4_2015/F1.py
libcnmc/cli_4_2015.py

- Se puede elegir la zona de calidad del CT o del Municipio.
- libcnmc/cir_4_2015/F1.py
- libcnmc/cli_4_2015.py

Añadida la opción de elección la zona de calidad.

---

libcnmc/cir_4_2015/F15.py

- Arreglar datos del tramo en el F15
- F15 4/2015

Arreglar datos del tramo en el F15

---

libcnmc/cir_4_2015/F1.py

-  Simplificar los parametros de busqueda
-   F1 4/2015

Simplificar parametros de busqueda

---

libcnmc/res_4666/AUD_FIA.py

- Eliminar variables sin usar
- FIA 4666

Eliminar variables sin usar

---

libcnmc/cir_4_2015/F16.py

- Añadir posicion y nodo para el fichero 16
- F16 4/2015

Read node_id for condensadors

---

libcnmc/cir_4_2015/F1.py

- Rellenar datos de x y y del F1
- F1 4/2015

Rellenar datos de x y y del F1

---

libcnmc/cir_4_2015/F1.py

- Comprovar si raven esta disponible
- F1 4/2015

Comprovar si raven esta disponible

---

libcnmc/utils.py

- Gestionar cts sin nodo
- F15 4/2015

Gestionar cts sin nodo

---

libcnmc/cir_4_2015/F9.py

- Arreglar escritura del F9 4/2015
- F9 4/2015

Arreglar escritura del F9 4/2015

---

requirements.txt

- Avoid error with pyproj lib by forcing an especific version.
- requirements.txt

Force version for pyproj.

---

libcnmc/cir_4_2015/F11.py

- Añadir soprte para el modelo de cuadros BT
- F11 4/2015

Añadir soprte para el modelo de cuadros BT

---

libcnmc/cir_4_2015/F1.py

- The generation of the Dist code of the file was commented and replaced for a fix one by mistake.
- 4/2015: F1

Fix 4/2015-F1 distri code generation.

---

libcnmc/cir_4_2015/F11.py

- Arreglar retrocompatibilidad del fichero F11
- F11 4/2015

Arreglar retrocompatibilidad del fichero F11

---

libcnmc/cir_4_2015/F11.py

- Add elements with data baixa but active.
- 4/2015-F9

4/2015-F9: Add elements with data baixa but active.

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F16.py
libcnmc/cir_4_2015/F9.py
libcnmc/utils.py

- Add support for field 'geom' on 4/2015: F9.
- Improve functions:
- 'get_srid'
- 'convert_srid'
- Refactor usage of 'convert_srid' due a change on it's call on 4/2015 files.
- 4/2015: 
- F1
- F9
- F11
- F13
- F15
- F16
- Utils

Add support for field 'geom' on 4/2015: F9

---

libcnmc/utils.py

- Improve f15 compatibility
- F15 4/2015

Improve f15 compatibility

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py

- Fix start and end nodes on 4/2015: F10
- 4/2015: 
- F10AT
- F10BT

Fix start and end nodes on 4/2015: F10

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F14.py
libcnmc/cir_4_2015/F20.py

- Ensure that each tqdm description match with the file definition.
- 4/2015:
- F10AT
- F10BT
- F12
- F13
- F13C
- F13bis
- F14
- F20

Ensure that each tqdm desc match for each file obj.

---

libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F13bis.py

- Fix the TRAFO node get.
- 4/2015: F12, F13bis

Fix the trafo node retrivement.

---

libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/__init__.py
libcnmc/cli_4_2015.py

- Improve 4/2015: F15 checking only Cel·les
- 4/2015: F15

Improve 4/2015: F15 checking only Cel·les

---

libcnmc/cir_4_2015/F1.py

- Fix 4/2015-F1 get_tipus_connexio method
- 4/2015: F1

Fix 4/2015: F1 'get_tipus_connexio' method

---

requirements.txt

- Forzar versión 2.3 o inferior para progressbar.

Progressbar version

---

libcnmc/cir_4_2015/F1.py

- Se ha añadido una nueva condición en el if del 'Tipus A' donde se comprueba si existe el campo 'edge_id' para proseguir con el IF.
- F1.py

Añadir nueva condición para evaluar 'edge_id'

---

libcnmc/cli_4666.py

- Corregir el campo a comparar en el cliente del 4666
- libcnmc/cli_4666.py

Corregir compare field 4666

---

libcnmc/cli_4666.py
libcnmc/res_4666/LBT.py

- Corregir el calculo de los campos **origen** y **final** para los tramos de LBT en la 4666
- res_4666/LBT.py

Corregir la recuperacion del origen y finals para los tramos de LBT en la 4666

---

libcnmc/cli_4666.py

- No se genera el fichero de condensadores por falta del param -m
-

Delete trash code and fix condensadors with -m parameter

---

libcnmc/cir_4_2015/F9.py

- Fix 4/2015-F9: Ensure that, if it the elements have the column geom, it's filled
- cir_4_2015/F9.py

Fix 4/2015-F9: Ensure that, if it the elements have the column geom, it's filled

---

libcnmc/core/__init__.py
libcnmc/res_4666/LBT.py

- Corregir método que crea el fichero de modificaciones.
- Apply the ERP PR: https://github.com/gisce/erp/pull/10486
- libcnmc/core/__initi__.py

Arreglar condición de salida para fichero modif

---

libcnmc/audit_6181/CTS.py
libcnmc/audit_6181/DES.py
libcnmc/audit_6181/FIA.py
libcnmc/audit_6181/LAT.py
libcnmc/audit_6181/LBT.py
libcnmc/audit_6181/MAQ.py
libcnmc/audit_6181/POS.py
libcnmc/audit_6181/SE.py
libcnmc/cli_6181.py
libcnmc/core/__init__.py
libcnmc/utils.py

:warning: Se ha añadido un campo en la clase base MultiprocessBased para poder añadir una cabecera en los ficheros generados.
https://github.com/gisce/libCNMC/blob/da23b43b227be02ab72a88407e3ce32046eff1e8/libcnmc/core/__init__.py#L108-L109
- Añadir 'motivaciones' en el report 6181/2019 de inversiones.
- Añadir un flag para añadir una cabecera en los ficheros generados.
Necesita la PR: https://github.com/gisce/erp/pull/10292

Add 'Motivaciones' to the investments report

---

libcnmc/audit_6181/CTS.py
libcnmc/audit_6181/DES.py
libcnmc/audit_6181/FIA.py
libcnmc/audit_6181/LAT.py
libcnmc/audit_6181/LBT.py
libcnmc/audit_6181/MAQ.py
libcnmc/audit_6181/POS.py
libcnmc/audit_6181/SE.py
libcnmc/cli_6181.py
libcnmc/utils.py

- Arreglar formato de los campos de fecha, algunos decimales, y las comunidades autónomas.
-

Arreglar formato en algunos ficheros de la resolucion 6181

---

libcnmc/cir_4_2015/F15.py

- Conseguir el valor del campo "tramo" para los elementos de fiabilitat si no tiene el campo "tramo_id" informado. Se utilizan los modelos de polyline y edge para determinar el tramo del  elemento a partir de su vertice del bloque.
- 4/2015: F15

Fix o_tram calc on 4/2015 F15.

---

libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py

- Fix nodes on F10-AT-BT for Mapguide users on 4/2015
- 4/2015:
- F10AT
- F10BT

Fix nodes on F10-AT-BT for Mapguide users on 4/2015

---

libcnmc/cir_4_2015/F14.py

- Get the Parc codi and not the tension on the 4/2015: F14
- 4/2015: 
- F14

Get the Parc codi and not the tension on the 4/2015: F14

---

libcnmc/audit_6181/CTS.py
libcnmc/audit_6181/DES.py
libcnmc/audit_6181/FIA.py
libcnmc/audit_6181/LAT.py
libcnmc/audit_6181/LBT.py
libcnmc/audit_6181/MAQ.py
libcnmc/audit_6181/POS.py
libcnmc/audit_6181/SE.py
libcnmc/utils.py

- Adaptaciones para la generación de ficheros de inversiones según nueva resolución: 5759/2020

Adaptaciones a los formatos de la nueva resolución 6181

---

libcnmc/res_4666/CON.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

- Update the behavior of the field stat related to the field fecha_baja. If the element have fecha_baja the state must be 1.
- 4666:
- CON
- CTS
- FIA
- LAT
- LBT
- MAQ
- POS
- SUB

Update the behavior of the field stat related to the field fecha_baja

---

libcnmc/core/__init__.py

Fix multiprocess output_m queue

---

libcnmc/utils.py

- Only use available CPUs throught number of CPUs and load average

Only use available CPUs

---

libcnmc/utils.py
requirements.txt

- Avoid old pyproj version
- refactor `convert_srid` 
- utils.py

Upgrade pyproj version

---

libcnmc/cir_8_2021/FA1.py
libcnmc/cir_8_2021/FA2.py
libcnmc/cir_8_2021/FA3.py
libcnmc/cir_8_2021/FA4.py
libcnmc/cir_8_2021/FA5.py
libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB1_1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB2_1.py
libcnmc/cir_8_2021/FB2_2.py
libcnmc/cir_8_2021/FB3.py
libcnmc/cir_8_2021/FB3_1.py
libcnmc/cir_8_2021/FB3_2.py
libcnmc/cir_8_2021/FB3_3.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB5_2.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB7.py
libcnmc/cir_8_2021/FB8.py
libcnmc/cir_8_2021/FB9.py
libcnmc/cir_8_2021/FD2.py
libcnmc/core/__init__.py

Fix exit with token based

---

libcnmc/cir_8_2021/FA5.py

- Añade la lectura de las energias en el formulario A5 y resuelve errores
- A5

ADD Lee las energias en A5 y resuelve errores

---

.github/workflows/version.yml

Auto tag ci

---

.bumpversion.cfg

add bump config file

---

.github/workflows/version.yml

add git config ci

---

.github/workflows/version.yml

fix version type ci

---

.github/workflows/version.yml

add ssh ci

---

libcnmc/cir_8_2021/FD2.py

- Comprobar si esta instalado el módulo de seguimiento de casos
- FD2

Comprobar si esta instalado el módulo de seguimiento de casos

---

.github/workflows/version.yml

- **major**: Major auto version vX._._
- **minor**: Minor auto version v_.X._
- **patch**: Patch auto version v_._.X
- 
-

try with ssh-key checkout

---

.github/workflows/version.yml

Update CI: Skips version trigger from Bump commit

CI - check if bump commit

---

libcnmc/cir_8_2021/FA1.py
libcnmc/cir_8_2021/FB1.py

- Mejora el filtro de MODELO en el B1
- Mejora la POTENCIA_ADSCRITA en A1
- A1, B1

IMP Mejoras en MODELO - B1 y POTENCIA_ADSCRITA - A1

---

libcnmc/cir_8_2021/FB3_2.py
libcnmc/cir_8_2021/FB4.py

- Filtra los ids dependiendo del valor del campo "criteri_regulatori"
- B3.2, B4

ADD Filtro de ids en get_sequence según criteri_regulatori, B3.2 y B4

---

libcnmc/cir_8_2021/FA1.py

- Cambia el filtro de ids de las polizas. Ahora el search es igual al del F1 de la Cir4/2015
- A1

IMP Mejora el filtro de las polizas en el A1 para que se comporte como el F1 Cir. 4/2015

---

libcnmc/res_4666/AUD_CTS.py
libcnmc/res_4666/AUD_FIA.py
libcnmc/res_4666/AUD_LAT.py
libcnmc/res_4666/AUD_LBT.py
libcnmc/res_4666/AUD_POS.py
libcnmc/res_4666/CON.py
libcnmc/res_4666/CTS.py
libcnmc/res_4666/DES.py
libcnmc/res_4666/FIA.py
libcnmc/res_4666/LAT.py
libcnmc/res_4666/LBT.py
libcnmc/res_4666/MAQ.py
libcnmc/res_4666/MOD.py
libcnmc/res_4666/POS.py
libcnmc/res_4666/SUB.py

-  Se pasan todos los ficheros de la 4666 a StopMultiprocess
- CTS

Pasar la generació de los ficheros de la 4666 a StopMultiprocess

---

libcnmc/cir_8_2021/FA1.py

- Corrige los parametros de un search del A1
- A1

FIX Corrige los parametros de un search del A1

---

libcnmc/cir_8_2021/FA1.py

- Resuelve errores al rellenar el campo estado_contrato en el formulario A1 
- A1

FIX Resuelve la generación del A1, campo estado_contrato - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Corrige los parámetros del search para resolver errores del funcionamiento general al generar el A1. No encontraba modcons en la fecha solicitada
- A1

FIX Resuelve errores de funcionamiento debido al límite del search, A1 - Cir8/2021

---

libcnmc/cir_4_2015/F1.py
libcnmc/cir_4_2015/F10AT.py
libcnmc/cir_4_2015/F10BT.py
libcnmc/cir_4_2015/F11.py
libcnmc/cir_4_2015/F12.py
libcnmc/cir_4_2015/F12bis.py
libcnmc/cir_4_2015/F13.py
libcnmc/cir_4_2015/F13C.py
libcnmc/cir_4_2015/F13bis.py
libcnmc/cir_4_2015/F14.py
libcnmc/cir_4_2015/F15.py
libcnmc/cir_4_2015/F16.py
libcnmc/cir_4_2015/F1bis.py
libcnmc/cir_4_2015/F20.py
libcnmc/cir_4_2015/F9.py

-  Convertir el proceso 4/2015 a StopMultiprocess
- Todos los de la 4/2015

Convert 4/2015 to StopMultiprocess

---

libcnmc/cir_8_2021/FD2.py

- **major**: Major auto version vX._._
- **minor**: Minor auto version v_.X._
- **patch**: Patch auto version v_._.X
- Changes creation of tracking records.
- F2D

Migrate D2 case tracking to mongoDB

---

libcnmc/cir_8_2021/FA1.py

- Rectifica el nombre de una variable ya que esta ya se utilizaba en otra parte del código y provocaba errores
- A1

FIX Rectifica el nombre de una variable A1 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Mejoras en el cálculo de POTENCIA_ADSCRITA, BAJA_SUMINISTRO, CONEXION_AUTOCONSUMO
- A1

IMP Mejoras en A1

---

libcnmc/cir_8_2021/FA1.py

- Filtra las pólizas canceladas en el campo BAJA_SUMINISTRO A1- Cir8/2021
- A1

IMP Filtra las pólizas canceladas en el campo BAJA_SUMINISTRO A1- Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

-  Inicializa potencia_adscrita a 0 FA1
- A1

FIX Inicializa potencia_adscrita a 0 - A1 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Fuerza el valor abosulto del campo ENERGIA_EXCEDENTARIA
- A1

IMP Fuerza el valor abosulto del campo ENERGIA_EXCEDENTARIA - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

- Lee el CUPS de Servicios Auxiliares directamente de la Póliza
- A2

IMP Lee el CUPS de Servicios Auxiliares directamente de la Póliza - A2 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

-  Lee el CUPS de los Servicios Aux. de Pòliza en caso de no encontrarlo directamente - Cir8/2021
-  A1

IMP A1 Lee el CUPS de los Servicios Aux. de Póliza en caso de no encontrarlo directamente - Cir8/2021

---

libcnmc/cir_8_2021/FB2.py

- Usa el id_regulatori del CT si existe
- B2

IMP Usa el id_regulatori del CT si existe - B2 - Cir8/2021

---

libcnmc/cir_8_2021/FA5.py

- Mejora el formato de salida de algunos campos del formulario A5. 
- A5

IMP Pequeños cambios en A5 - Cir8/2021

---

libcnmc/cir_8_2021/FB2.py

- Corrige el nombre al buscar el id_regulatorio
- B2

FIX Corrige el nombre al buscar el id_regulatorio - B2 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Busca el contador aunque la póliza no este activa igual que se hacia en la 4/2015 
- A1

IMP Busca el contador aunque la póliza no este activa A1 - Cir8/2021 

---

libcnmc/cir_8_2021/FB6.py

- Mejoras en el filtro de IDs y el campo IDENTIFICADOR_ELEMENTO
- B6

IMP Añade mas tipos de celdas en el B6 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

- Corrige un error en el read, ahora accede directamente con el id 
- A2

FIX Corrige un error en el read de un modelo - A2 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py
libcnmc/utils.py

- Mueve la función para encontrar CUPS servicios aux a utils.py para ser utilizada desde el ERP
- A2, utils

IMP Mueve la función para encontrar CUPS servicios aux a utils.py

---

libcnmc/cir_8_2021/FA5.py

- Corrige la lectura del participante en el A5 - Cir8/2021
- A5

FIX Corrige la lectura del participante en el A5 - Cir8/2021

---

libcnmc/cir_8_2021/FB5.py

-  Corrige la lectura de un campo en el B5 - Cir8/2021
- B5

FIX Corrige la lectura de un campo en el B5 - Cir8/2021

---

libcnmc/cir_8_2021/FB5.py

- Corrige la lectura del campo MOTIVACION en B5
- B5

FIX Corrige la lectura del campo MOTIVACION en B5 - Cir8/2021

---

libcnmc/cir_8_2021/FB5.py

- Corrige el formato de VALOR_RESIDUAL en el B5 
- B5

FIX Corrige el formato de VALOR_RESIDUAL en el B5 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py
libcnmc/utils.py

- Resuelve conflictos al calcular las energias producidas y consumidas, activas/reactivas
- Mejora la función de búsqueda del CIL mediante el id del RE 
- A2, utils

IMP Mejoras en el cálculo de energias del A2 y la función de búsqueda del CIL - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

-  Lee la tensión directamente de la pòliza
- A2

IMP Lee la tensión directamente de la pòliza - A2 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py

- Varias mejoras en la lectura y formato de campos
- B1

IMP Varias mejoras en la lectura y formato de campos del B1 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Corrige el formato en el A1
- A1

IMP Corrige el formato en el A1

---

libcnmc/cir_8_2021/FA2.py
libcnmc/utils.py

- Corrige la lectura del CUPS de SSAA
- A2

FIX Corrige la lectura del CUPS de SSAA en el A2 - Cir8/2021

---

libcnmc/cir_8_2021/FA2.py

- Protege energias y CUPS SSAA si no hay ningún CUPS SSAA asociado
- A2

FIX Protege energias y CUPS SSAA si no hay ningún CUPS SSAA asociado - A2 - Cir8/2021 

---

libcnmc/cir_8_2021/FA2.py

- Corrige un error en la lectura del SSAA 
- A2

FIX Corrige un error en la lectura del SSAA - A2 - Cir8/2021

---

libcnmc/cir_8_2021/FB8.py

- Añade la lectura del campo DESCRIPCION
- B8

IMP Añade la lectura del campo DESCRIPCION en el B8 - Cir8/2021

---

libcnmc/cir_8_2021/FB6.py

- Corrige la lectura de la TENSION_CONSTRUCCION en el formulario B6
- B6

IMP Corrige la lectura de la TENSION_CONSTRUCCION en el formulario B6 - Cir8/2021

---

libcnmc/cir_8_2021/FD2.py

Reconocer y tratar correctamente los rechazos en b104

Correcciones en el trato de los rechazos de b104 - Circular 8/2021 - FD2

---

libcnmc/cir_8_2021/FB1.py

- FIX Lectura del campo punto forntera en AT 
- B1

FIX Lectura del campo punto forntera en AT - B1 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py

- El campo FINANCIADO se lee directamente de los modelos de AT, BT y CTs
- B1, B2

IMP El campo FINANCIADO se lee directamente de los modelos de AT, BT y CTs - Cir 8/2021

---

libcnmc/cir_8_2021/FB1.py

- Fuerza REACTANCIA, RESISTENCIA Y INTENSIDAD = 0,001 si son < 0.001 para cumplir con el valdiador
- B1

IMP REACTANCIA, RESISTENCIA Y INTENSIDAD = 0,001 si son < 0.001 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py

- Corrige la lectura de la potencia contractada en el A1 
- A1

FIX Corrige la lectura de la potencia contractada en el A1 - Cir8/2021

---

libcnmc/cir_8_2021/FD1.py

Corrección D1

---

libcnmc/cir_8_2021/FC2.py

- Añade la generación del formulario C2 
- C2, utils, cli_8_2021

IMP Añade la generación del formulario C2

---

libcnmc/cir_8_2021/FB6.py

-  Corrige la lectura de las líneas asociadas a un soporte
- B6

IMP Corrige la lectura de las líneas asociadas a un soporte B6 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py

- Modifica el sequence del B1
- B1

IMP Modifica el sequence del B1 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py

- IMP MOTIVACION y TIPO_INVERSIÓN vacío cuando hay FECHA_BAJA
- B1

IMP MOTIVACION y TIPO_INVERSIÓN vacío cuando hay FECHA_BAJA

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py

- Modifica el comportamiento del campo ESTADO

IMP Modifica el comportamiento del campo ESTADO

---

libcnmc/cir_8_2021/FA5.py

- '0,000' cuando el valor es '0' para cumplir con el validador Cir8/2021
- A5

IMP '0,000' cuando el valor es '0' para cumplir con el validador Cir8/2021

---

libcnmc/cir_8_2021/FB2_2.py

- Busca celdas de baja al buscar la máquina - Cir8/2021
- B2.2

IMP Busca celdas de baja al buscar la máquina - Cir8/2021

---

libcnmc/cir_8_2021/FB6.py

- Corrige la lectura del campo Municipio
- B6

IMP Corrige la lectura del campo Municipio B6 - Cir8/2021

---

libcnmc/cir_8_2021/FB2.py

- Corrige el formato del campo FIANACIADO en el formulario B2
- B2

IMP Formato en FINANCIADO B2

---

libcnmc/cir_8_2021/FB1.py

- Corrige el número de decimales
- B1

IMP Deciamles de FINANCIADO en B1 - Cir8/2021

---

libcnmc/cir_8_2021/FB1_1.py

- Añade el filtro de criterio regulatorio
- B1.1

IMP Filtro de criterio regulatorio en B1.1 - Cir8/2021

---

libcnmc/cir_8_2021/FA1.py
libcnmc/cir_8_2021/FA2.py
libcnmc/cir_8_2021/FA3.py
libcnmc/cir_8_2021/FB1_1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB3.py
libcnmc/cir_8_2021/FB3_1.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB7.py

-  Coordenada Z a '0,000' en todos los formularios que la incluyen.
- A1, A2, A3, B1.1, B2, B3, B3.1, B6, B7

IMP Coordenada Z a '0,000' - Cir 8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py

- Corrige el campo FINANCIADO cuando es 0
- B1, B2

FIX Corrige el campo FINANCIADO cuando es 0 - Cir8/2021

---

libcnmc/cir_8_2021/FB1_1.py

- Utilizar el nombre del tramo para el código de segmento

Utilizar el nombre del tramo para el código de segmento para el fichero B1.1

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB2_1.py
libcnmc/cir_8_2021/FB3_3.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py

- Modifica el comportamiento de TIPO_INVERSION y OPERACION según el valdiador
- B1, B2, B2.1, B3.3, B4, B5, B6

IMP Modifica el comportamiento de TIPO_INVERSION y OPERACION según el valdiador - Cir8/2021

---

libcnmc/cir_8_2021/FD1.py

- Potencia con 3 decimales
- D1

IMP Potencia con 3 decimales D1 - Cir8/2021

---

libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB5.py

- Fuerza NUDO_BAJA = NUDO_ALTA según CINI 
- B2, B5

IMP Fuerza NUDO_BAJA = NUDO_ALTA según CINI - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py

-  Mejora el filtro de obras cuando hay más de una obra asociada

IMP Mejora el filtro de obras cuando hay más de una obra asociada - Cir8/2021

---

libcnmc/cir_8_2021/FC1.py

- Corrige la obtención del código INE de la Comunidad Autónoma en el C1.
- C1

FIX Código CCAA

---

libcnmc/core/__init__.py

- Añade campos al importador de CUPS.csv
- Cli

IMP Añade campos al importador de CUPS.csv

---

libcnmc/cir_8_2021/FB1.py

- OPERACION vacío si MODELO=M
- B1

IMP OPERACION vacío si MODELO=M - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py

- TIPO_INVERSION vacío si hay FECHA_BAJA
- B1, B2, B4, B5, B6

IMP TIPO_INVERSION vacío si hay FECHA_BAJA - Cir8/2021

---

libcnmc/cir_8_2021/FB9.py

-  Quita las referencias en el B9
- B9

IMP Quita las referencias en el B9 - Cir8/2021

---

libcnmc/cir_8_2021/FB9.py

- Filtra solo los registros con tipo de inversión
- B9

IMP Filtra solo los registros con tipo de inversión B9 - Cir8/2021

---

libcnmc/core/__init__.py

UpdateFile migrated to StopMultiprocess

UpdateFile migrated to StopMultiprocess

---

.github/workflows/release.yml

FIX Versión de Python

---

libcnmc/cir_8_2021/FA3.py

- Lee directamente los valores x y del A3 - Cir8/2021
- A3

IMP Lee directamente los valores x y del A3 - Cir8/2021

---

libcnmc/models/cnmcmodel.py

- Borra atributos innecesarios del modelo CNMC
- models

IMP Borra atributos innecesarios del modelo CNMC

---

libcnmc/cir_8_2021/FB1_1.py

- Segmento a 22 carácteres B1.1. - Cir 8/2021
- B1.1

IMP Segmento a 22 carácteres B1.1. - Cir 8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py

- Fuerza TIPO_INVERSION = 0 y ESTADO = 1 SI MODELO = M
- B1, B2, B4, B5, B6

IMP TIPO_INVERSION = 0 y ESTADO = 1 si MODELO = M - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py

- Fuerza que ESTADO no puede ser 2 si FECHA_APM < 2022

IMP ESTADO no puede ser 2 si FECHA_APM < 2022

---

libcnmc/cir_8_2021/FD2.py

- El formato era incorrecto 
- FD2

 Corregir el formato por el cual se buscan los casos Cir 8/2021 - FD2

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py

- ESTADO según FECHA_APS y MODELO

IMP ESTADO según FECHA_APS y MODELO

---

libcnmc/cir_8_2021/FB9.py

- Añade campos faltantes en B9 según validador
- B9

ADD Añade campos faltantes en B9 según validador

---

libcnmc/cir_8_2021/FB9.py

- Añade los campos faltantes del validador B9 - Cir8/2021
- B9

ADD Añade los campos faltantes del validador B9 - Cir8/2021

---

libcnmc/cir_8_2021/FD1.py

- Corrige decimales potencia D1
- D1

IMP Corrige decimales potencia D1 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py

- Corrige un error al leer TENSION_CONSTRUCCION BT - Cir8/2021
- B1

FIX Corrige un error al leer TENSION_CONSTRUCCION BT - Cir8/2021

---

libcnmc/models/res_4666/f7_4666.py

- Corrige la comparación de ESTADO del B6
- B6

FIX Corrige la comparación de ESTADO del B6 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py

- FECHA_IP vacía si hay FECHA_BAJA - Cir8/2021
- B1, B2, B4, B5

IMP FECHA_IP vacía si hay FECHA_BAJA - Cir8/2021

---

libcnmc/cir_8_2021/FB9.py

-  Fuerza el valor positivo de un campo del B9
- B9

IMP Fuerza el valor positivo de un campo del B9 - Cir8/2021

---

libcnmc/cir_8_2021/FD1.py

- Corrige el campo CCAA en el D1
- D1

IMP Corrige el campo CCAA en el D1 - Cir8/2021

---

libcnmc/cir_8_2021/FB2.py

- NUDO_ALTA = NUDO_BAJA si CINI[7] = Z o V
- B2

IMP NUDO_ALTA = NUDO_BAJA si CINI[7] = Z o V - B2 - Cir8/2021

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB6.py

- Lee id_regulatorio si existe en IDENTIFICADOR_BAJA 
- B1, B2, B6

ADD Lee id_regulatorio si existe en IDENTIFICADOR_BAJA - Cir8/2021

---

libcnmc/cir_8_2021/FB9.py

- Corrige la lectura de los campos 5_G_8 i 5_G_9 del formulario B9
- B9

FIX Corrige la lectura de los campos 5_G_8 i 5_G_9 del formulario B9 - Cir8/2021

---

libcnmc/cir_8_2021/FB2_1.py
libcnmc/cir_8_2021/FB2_2.py
libcnmc/cir_8_2021/FB3_3.py

- **major**: Major auto version vX._._
- **minor**: Minor auto version v_.X._
- **patch**: Patch auto version v_._.X
- Se utiliza `id_regulatori` siempre que exista en los ficheros B2.1, B2.2, B3.3.
- `FB2_1.py`
- `FB2_2.py`
- `FB3_3.py`

Añadir el campo id_regulatori en B2.1, B2.2, B3.3

---

libcnmc/cir_8_2021/FB2_2.py

Utilitzar tipus element per saber interruptor

Utilitzar tipus element per saber interruptor

---

libcnmc/res_4667/CT.py
libcnmc/res_4667/DES.py
libcnmc/res_4667/FIA.py
libcnmc/res_4667/LAT.py
libcnmc/res_4667/LBT.py
libcnmc/res_4667/MACRO.py
libcnmc/res_4667/MAQ.py
libcnmc/res_4667/Otros.py
libcnmc/res_4667/POS.py
libcnmc/res_4667/PRO.py
libcnmc/res_4667/RES.py
libcnmc/res_4667/RES_CCAA.py

- Convertimos los scripts de la 4667 a `StopMultiProcess` 
- Todos los de la RES4667

Convert RES4667 to StopMultiProcess

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py
libcnmc/cir_8_2021/FB8.py
libcnmc/models/cnmcmodel.py

- Añadimos la comparación con los ficheros de la circular 8/2021

Comparación con ficheros de la Circular 8/2021

---

libcnmc/core/__init__.py

- Compatible con rave/sentry
- core

Try compat sentry_sdk/raven

---

libcnmc/cir_8_2021/FB6.py

- filtramos fiabilidad y CINI I26
- B6

B6: filtramos fiabilidad y CINI I26

---

libcnmc/cir_8_2021/FB3_3.py

- Añadimos condensadores en el fichero B3.3
- B3.3
- https://github.com/gisce/erp/pull/19847

Añadimos condensadores en el fichero B3.3

---

libcnmc/cir_8_2021/FA4.py
libcnmc/cli_8_2021.py

- Tener en cuenta los CONTA-AT en los ficheros A4
- A4

A4: Tener en cuenta los CONTA-AT

---

libcnmc/cir_8_2021/FB5.py

- Añadimos los condensadores de subestación en los ficheros B5
- B5

B5: Añadimos los condensadores

---

libcnmc/cir_8_2021/FA1.py

- A1: Informar con valor 2 en la columna `AUTOCONSUMO` si este es colectivo
- A1
- Closes #634

A1: Informar si autoconsumo colectivo

---

libcnmc/cir_8_2021/FB5.py

- Corrección código del nodo en los condensadores (cogía el id interno) en el B5
- B5

B5: Corrección código del nodo en condensadores

---

libcnmc/cir_8_2021/FA1.py

- A1: Millorem el càlcul de la potencia adscrita agafant la màxima dels butlletins vigents en data de circular
- A1

A1: Millorem el càlcul de la potencia adscrita

---

libcnmc/cir_8_2021/FB2_2.py

- B2.2: Se añade el filtro que no sean del tipo `FUS_AT`
- B2.2

B2.2: Se añade el filtro que no sean del tipo FUS_AT

---

libcnmc/cir_8_2021/FA1.py

- A1: Corregir si un cups no tenía boletín no salía en el listado
- A1

A1: Arreglar si no tienen boletín no falle

---

libcnmc/utils.py

- A1: Si no encuentra un tramo BT busca en AT
- A1

A1: Mejora tipos de conexión en CONTA-AT

---

libcnmc/cir_8_2021/FB9.py

- Arreglar la forma de calcular los valores de los campos `5_G_8` y `5_G_9` sobre la inversión realizada en instalaciones financiadas parcial o totalmente por terceros. 
- B9

FIX Calculo conceptos 5_G_8 y 5_G_9 del B9

---

libcnmc/cir_8_2021/FB2.py

- Se pasa de `V` a `kV` si el campo `tensio_entrant` existe.
- `FB2.py`

FIX pasar de V a kV con el nuevo campo tensio_entrant

---

libcnmc/cir_8_2021/FA1.py
libcnmc/cli_8_2021.py

- Añadir flag para indicar que la tensión se extraerá de la modificación contractual asociada a la póliza de un CUPS.
- A1
Esta PR ha de ser integrada antes:
- https://github.com/gisce/erp/pull/21020

A1: Opcion para extraer la tension del contrato

---

libcnmc/cir_8_2021/FB9.py

- Filtrar datos por campo modelo igual a 'I':Inventario

B9: IMP Filtrar datos por modelo igual a 'I':Inventario)

---

libcnmc/cir_4_2015/F9.py
libcnmc/core/__init__.py

- Hacer el código de la librería compatible con Python3 
- Core
- F9 cir4_2015

IMP hacer libcnmc compatible con Py3

---

libcnmc/cir_8_2021/FA1.py

- Extraer la potencia adscrita del nuevo modelo estadisticas de un CUPS
- A1

A1: Cambiar la forma de extraer la potencia adscrita de un CUPS

---

libcnmc/cir_8_2021/FB2.py

- Arreglar error de 
```
UnboundLocalError: local variable 'fecha_baja' referenced before assignment                                                                   
Traceback (most recent call last):Transformación:  19% |##########################################                | ETA:  0:02:43
File "/home/erp/local/lib/python2.7/site-packages/libcnmc/cir_8_2021/FB2.py", line 376, in consumer
fecha_baja, 
```
TASK-[72502](http://10.246.0.198/action?model=project.task&views=%5B%5B263%2C%22tree%22%5D%2C%5B1129%2C%22form%22%5D%2C%5B265%2C%22calendar%22%5D%2C%5B266%2C%22gantt%22%5D%2C%5B1267%2C%22graph%22%5D%5D&title=Totes+les+tasques&initialView=%7B%22id%22%3A1129%2C%22type%22%3A%22form%22%7D&action_type=ir.actions.act_window&action_id=273&res_id=72502&treeExpandable=false&limit=80)
- B2

Arreglar error de variable referenciada antes de asignarla

---

libcnmc/cir_8_2021/FB1.py
libcnmc/cir_8_2021/FB2.py
libcnmc/cir_8_2021/FB4.py
libcnmc/cir_8_2021/FB5.py
libcnmc/cir_8_2021/FB6.py

- Si model es E però no es troba asociat a cap treball ja que no es modifica, llavors `tipo_inversion` no ha de ser 0.
- B1, B2, B4, B5, B6

Vincular estado a modelos E para tipo inversion

---

libcnmc/cir_8_2021/FB2.py

- No se usaba datetime y se recogía la fecha de baja con formato tipo `2024-07-08` cuando debe ser `08/07/2025` 
- B2

Arreglo fecha de baja en trabajo ct para B2
